MITRE_MAP = {
    "User logs in from new location": "Initial Access",
    "Multiple failed login attempts": "Credential Access",
    "MFA disabled": "Defense Evasion",
    "New login from IP": "Initial Access",
    "PowerShell used to list AD users": "Discovery",
    "Password reset request from unfamiliar location": "Credential Access",
    "Brute-force attack detected": "Credential Access",
    "Suspicious login pattern (same time every day)": "Credential Access",
    "Login from TOR network": "Initial Access",
    "Remote Desktop session started": "Lateral Movement",
    "Accessed C$ share on another machine": "Lateral Movement",
    "Used PSExec to run remote command": "Lateral Movement",
    "Account used on multiple systems": "Credential Access",
    "Suspicious admin tool downloaded": "Execution",
    "Remote PowerShell command execution": "Lateral Movement",
    "Admin account used on non-administrative systems": "Lateral Movement",
    "Credential dump from system memory": "Credential Access",
    "Mimikatz or other credential dump tool detected": "Credential Access",
    "Large file compressed": "Collection",
    "File uploaded to unknown domain": "Exfiltration",
    "Tor process detected": "Command and Control",
    "External device plugged in": "Collection",
    "Traffic to Dropbox observed": "Exfiltration",
    "Massive data download initiated": "Exfiltration",
    "Large volume of data being transferred at odd hours": "Exfiltration",
    "Unusual cloud storage access": "Exfiltration",
    "Data transferred to external IP address": "Exfiltration",
    "Exploit found in system to gain root/admin access": "Privilege Escalation",
    "Sudo command executed by non-privileged user": "Privilege Escalation",
    "Unauthorized use of admin credentials": "Privilege Escalation",
    "System security settings changed unexpectedly": "Defense Evasion",
    "Zero-day exploit attempt detected": "Initial Access",
    "Modification of /etc/sudoers or similar privilege files": "Privilege Escalation",
    "Privilege escalation via unpatched vulnerability": "Privilege Escalation",
    "Files being renamed with a specific ransom extension": "Impact",
    "Unusual file encryption activity detected": "Impact",
    "Suspicious file extensions being added to files": "Impact",
    "Ransom note found on multiple systems": "Impact",
    "Malicious attachment in email opened": "Execution",
    "Email from seemingly legitimate source requesting credentials": "Phishing",
    "Unusual domain name in email sender's address": "Phishing",
    "User clicked on link from phishing email": "Phishing",
    "Redirect from known site to a phishing page": "Phishing",
    "Suspicious email with a sense of urgency (e.g., 'Immediate Action Required')": "Phishing",
    "Unusual file type attached to email (e.g., .exe, .zip)": "Phishing",
    "Fake login page detected": "Phishing",
    "Unexpected increase in network traffic from one source": "Denial of Service",
    "Server is unreachable due to high traffic": "Denial of Service",
    "High rate of HTTP requests detected": "Denial of Service",
    "ICMP flood detected": "Denial of Service",
    "UDP flood observed": "Denial of Service",
    "Server performance degraded due to excessive requests": "Denial of Service",
    "Network device performance impacted due to DDoS": "Denial of Service",
    "Suspicious volume of SYN packets being sent": "Denial of Service",
    "Malicious code inserted into third-party software update": "Supply Chain",
    "Unexpected changes in software dependencies": "Supply Chain",
    "Abnormal activity in a trusted vendor's network": "Supply Chain",
    "Compromised update downloaded from a trusted source": "Supply Chain",
    "Unexpected change in software version from trusted repository": "Supply Chain",
    "Legitimate software package modified with malicious code": "Supply Chain",
    "Employee accessing sensitive data without authorization": "Insider Threat",
    "Employee transferring files to an external device": "Insider Threat",
    "Unusual pattern of access to critical infrastructure": "Insider Threat",
    "Employee leaves organization with sensitive data": "Insider Threat",
    "Increased use of privileged access by non-administrators": "Insider Threat",
    "Employees accessing files not relevant to their job role": "Insider Threat",
    "Unauthorised user gaining access via compromised employee account": "Insider Threat",
    "User logs in after hours without valid reason": "Insider Threat"
}
